name: Changesets
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    uses: driimus/shared-workflows/.github/workflows/publish.yml@main
    secrets: inherit
